using ProjectTemplates;

using System;
using System.Collections.Generic;
using System.Text;

namespace EulerCSharp
{
    [EulerProblem(Language.CSharp, 2, "Even Fibonacci numbers",
        "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:\n\n" +
        "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n\n" +
        "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.")]
    public class Problem002 : IEulerProblem
    {
        public string RunSolution()
        {
            var fib = new Fibonacci(1, 2);
            var value = 0L;

            foreach(var nextFib in fib)
            {
                if (nextFib >= 4_000_000)
                    break;

                if (nextFib % 2 == 0)
                    value += nextFib;
            }

            return value.ToString();
        }
    }
}
